name: Docker Build and Push

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: node945
          password: dckr_pat__D7MKY2lVv2En2Bo1HmACpNnmps

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          run: |
          docker buildx build \
            --iidfile /tmp/docker-actions-toolkit-ifiwFn/iidfile \
            --tag node945/PyApis:latest \
            --metadata-file /tmp/docker-actions-toolkit-ifiwFn/metadata-file \
            --push .
